# Generated by Django 4.2 on 2025-01-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Electrico'), ('A', 'Agua'), ('R', 'Roca'), ('T', 'Tierra'), ('P', 'Planta'), ('F', 'Fuego')], max_length=30),
        ),
    ]
